### ISSUE TITLE
Will the project support U200？

### ISSUE THREAD

**Issue by TimmonSha** [Xilinx/open-nic-shell#1]
Hope to use it on U200 board.

**Comment by cneely-xlnx** [comment]
Currently, OpenNIC supports the U250 and U280 as targets, with a university group currently adding U50 support.  We believe that it should be fairly easy to port the U250 version to U200, and so we encourage any interested person in the community to do this.

**Comment by raph38130** [comment]
also interested by u50 support. is it possible to reach the university group ?

**Comment by cneely-xlnx** [comment]
In terms of the port for the U50 board, there is some brief info within this post:
https://github.com/Xilinx/open-nic-driver/issues/4
