### ISSUE TITLE
Other versions of Vivado supported?

### ISSUE THREAD

**Issue by laochonlam** [Xilinx/open-nic-shell#12]
Hi OpenNIC developers,

I just found out that OpenNIC only supports 2020.2. Is there possible to use OpenNIC in other versions like 2020.1?

Thanks,
Lam

**Comment by cneely-xlnx** [comment]
Hi @laochonlam,
 Often on major new releases of Vivado, sometimes IPs will slightly different parameters or sometimes the names of some of the ports change.  That is the reason for the version check in the build.tcl script.  However, you can safely change that version check by editing the script to be other new or recent versions, e.g. 2021.1 or 2021.2.
Best regards,
--Chris

**Comment by laochonlam** [comment]
Hi @cneely-xlnx,

Thanks for your reply. I made some changes(https://github.com/laochonlam/open-nic-shell/commit/dc1d10980955bb1cffaf03b70fd41dbb6770d088) in the parameters of QDMA IP to compile and run successfully in Vivado 2020.1. Basically just followed the first [commit](https://github.com/Xilinx/open-nic-shell/tree/2d5531f2b217ad315a9c244f1e977eb813137aa9) on this repository. 

If OpenNIC plans to support backward I am happy to generalize it and contribute.

Thanks,
Lam

**Comment by cneely-xlnx** [comment]
Hi @laochonlam,

Thanks, I think that it might make sense to make a small note of this as a discussion topic on this site that you have some example modifications for backwards Vivado compatibility.  

In terms of code that is checked in, I think it's more important to try to keep the code up to date for recent versions of Vivado.  At least I want to encourage people to use recent versions of Vivado if possible, and to keep moving forward when possible.

Best regards,
--Chris

**Comment by laochonlam** [comment]
Cool! Thanks for the reply @cneely-xlnx.

Best,
ChonLam
