### ISSUE TITLE
Timing closure problem with Alveo U200 and 2 interfaces

### ISSUE THREAD

**Issue by alacamester** [Xilinx/open-nic-shell#14]
Hi!

I generated the project with command:
vivado -mode tcl -source build.tcl -tclargs -board_repo G:/Xilinx/Vivado/2020.2/data/boards/board_files -board au200 -num_phys_func 2 -num_cmac_port 2
(i added the "num_phys_func" argument bcause the included user plugin-box needed it)

The project builds with Vivado 2020.2, but with timing closure errors on the PCIe clock:
![opennic_timefail](https://user-images.githubusercontent.com/86793985/156507475-88fdc551-55bd-4714-aea9-def6b0a29cbf.png)

Project builds with 1 interface without problem.

L.

**Comment by cneely-xlnx** [comment]
Hi @alacamester,

Have you already tried increasing the Vivado Place and Route effort, e.g. by selecting under Tools->Settings->Implementation->Implementation Strategy a more aggressive strategy like Performance Explore?  (Also, that failing path in your screenshot is only off by a tiny amount, and I'd expect that generated implementation to probably still run okay on the board.)

Best regards,
--Chris

**Comment by cneely-xlnx** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/84047881/156673828-f55318f3-2f6f-43d5-a1b3-43a877540b52.png">

**Comment by alacamester** [comment]
Thanks for your answer, I'll try that.

Another "future proof" solutions that I can think of:

1. changing placement constraints (to bring PCIe logic closer to the PCIe hard component)
2. ease timing by logic relaxation, extra registers etc. (like in the old ISE days ;) )

What do you think about that? If I have more time I can look into it.

Thanks,
L.

**Comment by alacamester** [comment]
Changing the implementation effort level solved the issue for now. (but this could be a problem later, when someone adds extra logic...)
