### ISSUE TITLE
Question about "cmac_usplus_1_au280.tcl"

### ISSUE THREAD

**Issue by Vic0428** [Xilinx/open-nic-shell#16]
Hi all,

Thanks for your contributing the great OpenNIC project! And I have one question about `GT_LANE` configuration in `cmac_usplus_1_au280.tcl`

```
    CONFIG.CMAC_CORE_SELECT {CMACE4_X0Y7}
    CONFIG.GT_GROUP_SELECT {X0Y44~X0Y47}
    CONFIG.LANE1_GT_LOC {X0Y40}
    CONFIG.LANE2_GT_LOC {X0Y41}
    CONFIG.LANE3_GT_LOC {X0Y42}
    CONFIG.LANE4_GT_LOC {X0Y43}
```
It seems that the `LANEx_GT_LOC` and `GT_GROUP_SELECT` are mismatch. Or there are some reasons behind that? 

Really appreciate for your help!

~Vic

**Comment by cneely-xlnx** [comment]
Hi @Vic0428,

Thanks, for spotting that. I agree that the mismatch looks like a bug, and I think that these should be consistent.  

Effectively, in the implementation X0Y44~X0Y47 from that GROUP_SELECT are being used by cmac_us_plus1 (highlighted in pink below), and X0Y40~X0Y43 are being used by cmac_us_plus0 (highlighted in green below).  

(My mouse curser didn't get captured in the screenshot.  It was hovering over MGT X0Y47 which was the towards/on the top of that group, which is what the pop up is describing, although the pop up is slightly lower.) 

I wanted to ask, if you would you be willing to submit a pull request with the code change to correct the lane assignments by following the pattern used in the others (in the interest of encouraging contributions from the community)?  Please let me know.

Best regards,
--Chris

<img width="748" alt="image" src="https://user-images.githubusercontent.com/84047881/160039665-83357e30-481d-4c15-9362-cd0bfddf2783.png">

**Comment by Vic0428** [comment]
Sure! Let's me submit the PR tomorrow :)
