### ISSUE TITLE
 Is the definition of MAC port in "tuser_src" invalid?

### ISSUE THREAD

**Issue by maswx** [Xilinx/open-nic-shell#54]
I noticed that the "s_axis_c2h_tuser_src" in the file "qdma_subsystem_function" is not being used, even though it is described as an interface for describing the source MAC port and source PCIe-PFs in [Page10. ](https://github.com/Xilinx/open-nic/blob/main/OpenNIC_manual.pdf)

Is this a bug?

Similarly, I found that "m_axis_h2c_tuser_src" only operates as follows: "254 assign m_axis_h2c_tuser_src = 16'h1 << FUNC_ID". This means it only operates on PCIe-PFs and doesn't affect MAC ports,which contradicts the description in document [P10](https://github.com/Xilinx/open-nic/blob/main/OpenNIC_manual.pdf) where bits[15:6] are supposed to represent MAC ports.

**Comment by cneely-amd** [comment]
The QDMA subsystem is concerned with the PCIe side and has parts of it organized by FUNC_ID.
The CMAC subsystem contains packet_adapter modules specifically: packet_adapter_rx and packet_adapter_tx that are involved in setting and checking the MAC-related portions of the tuser_src and tuser_dst.

**Comment by maswx** [comment]
Thanks!
