### ISSUE TITLE
U55N: program/flash FPGA image without usb blaster

### ISSUE THREAD

**Issue by JunPhilips** [Xilinx/open-nic-shell#58]
we need to run a few U55N remotely. just wonder if they can be programmed/flashed without usb blaster? https://support.xilinx.com/s/article/71757?language=en_US says revert to factory mode can be done by either vivado (with usb blaster) or xbmgmt (without usb blaster). However, once taking over by open-nic driver, xbmgmt can't find devices anymore.
Thanks.

**Comment by cneely-amd** [comment]
Hi @JunPhilips the open-nic-shell contains the CMS and QSPI IP.

A more generic step-by-step example of using xbflash is described in this support article for general Alveo:
https://support.xilinx.com/s/article/Alveo-Updating-Vivado-images-via-PCIe-with-xbflash?language=en_US

The OpenNIC shell CMS address offsets are set within the system configuration block:
https://github.com/Xilinx/open-nic-shell/commit/416acbade8dcbcdba6e06564b3d2ca0ffc26ab62#diff-ccb916de505739fa603dcc0a7c85a9a06482f3dd268b550729c833d5a2031a9b

**Comment by JunPhilips** [comment]
Thanks very much!
