### ISSUE TITLE
cmac_usplus_1 module problem.

### ISSUE THREAD

**Issue by H0TSUN** [Xilinx/open-nic-shell#59]
Hello, 

I installed an alveo u50 card on each of the two servers. The programming cable has been cross-connected.  
 My enviroment is  below.
```
System Configuration
  OS Name              : Linux
  Release              : 5.15.0-91-generic
  Version              : #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023
  Machine              : x86_64
  CPU Cores            : 32
  Memory               : 128460 MB
  Distribution         : Ubuntu 20.04.6 LTS
  GLIBC                : 2.31
  Model                : X12DPi-N(T)6

XRT
  Version              : 2.13.466
  Branch               : 2022.1
  Hash                 : f5505e402c2ca1ffe45eb6d3a9399b23a0dc8776
  Hash Date            : 2022-04-14 17:43:11
  XOCL                 : unknown, unknown
  XCLMGMT              : unknown, unknown


Devices present
  0 devices found
BDF  :  Shell  Platform UUID  Device ID  Device Ready*

* Devices that are not ready will have reduced functionality when using XRT tools
```

I want to test the OPEN-NIC DPDK driver. This requires using two CMAC ports. So, I used the command below:
`
vivado -mode tcl -source build.tcl -tclargs -board au50 -jobs 32 -synth_ip 1 -impl 1 -post_impl 1 -num_phys_func 2 -num_cmac_port 2
`
However, it cannot find cmac_usplus1 module. I think this is because the cmac_usplus_1_au50.tcl file is missing. (https://github.com/Xilinx/open-nic-shell/tree/main/src/cmac_subsystem/vivado_ip)
I can make a bit stream if I use with num_cmac_port 1 argument.
How can I resolve this issue?

The result is
<img width="1115" alt="Pasted Graphic" src="https://github.com/Xilinx/open-nic-shell/assets/38975081/a63d45ee-6f39-4cb6-80b0-c81ff8a4e7f6">

Thanks!

**Comment by cneely-amd** [comment]
Hi @H0TSUN ,

Please double check that the Alveo U50 is what you are intending to use because I believe it has just a single (/ 1x100Gbps) port.

https://www.xilinx.com/publications/product-briefs/alveo-u50-product-brief-v2.pdf

Best regards,
--Chris

**Comment by H0TSUN** [comment]
Hello, @cneely-amd! Thank you for your reply.

I am trying the documentation of the dpdk driver (https://github.com/Xilinx/open-nic-dpdk), which uses 2 cmac ports. So I misunderstood that all cards support two CMAC ports.
